version: '3.7'

services:
  mercure-db:
    image: postgres:latest
    container_name: mercure-db
    restart: always
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      - POSTGRES_DB=mercure
      - POSTGRES_USER=mercure_user
      - POSTGRES_PASSWORD=mercure_password
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql
      - ./mercure-db/sql:/docker-entrypoint-initdb.d/

  mercure-cache:
    container_name: mercure-cache
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data

  mercure-pgadmin:
    image: dpage/pgadmin4
    container_name: mercure-pgadmin4
    restart: always
    depends_on:
      - mercure-db
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@mercure.com
      PGADMIN_DEFAULT_PASSWORD: mercure
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./mercure-db/servers.json:/pgadmin4/servers.json
      - ./mercure-db/pgpass:/pgpass

  mercure-api:
    image: mercure-api:dev
    container_name: mercure-api
    depends_on:
      - mercure-db
      - mercure-cache
    build:
      context: mercure-api
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    environment:
      - DOTNET_WATCH_RESTART_ON_RUDE_EDIT=1
      - DOTNET_WATCH_SUPPRESS_EMOJIS=1  
      - ASPNETCORE_ENVIRONMENT=Development
      - RUN_IN_DOCKER=true
    volumes:
      - ./mercure-api:/app
    command: dotnet watch run --project mercure.API
      
  mercure-web:
    image: mercure-web:dev
    container_name: mercure-web
    restart: unless-stopped
    build:
      context: mercure-web
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    volumes:
      - ./mercure-web:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 4200:4200
      - 49153:49153

volumes:
  pgdata:
  pgconf:
  pglog:
  pgadmin-data:
  cache:
      driver: local
