global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - scheme: http
    timeout: 10s
    api_version: v1
    static_configs:
    - targets: []
      
scrape_configs:
- job_name: TrackMercureAPIUsage  
  scrape_interval: 10s  
  scrape_timeout: 15s  
  metrics_path: /metrics  
  scheme: http  
  static_configs:  
  - targets:  
    - host.docker.internal:5000
  
- job_name: TrackPostgresUsage  
  scrape_interval: 10s  
  scrape_timeout: 15s  
  metrics_path: /metrics  
  scheme: http  
  static_configs:  
  - targets:  
    - host.docker.internal:9187