name: Mercure Web Testing

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18]

    steps:
      - uses: actions/checkout@v3
        
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: mercure-web/npm-shrinkwrap.json

      - run: npm ci
        working-directory: ./mercure-web
          
      - run: npm run test
        working-directory: ./mercure-web
